# Generated by Django 5.1.4 on 2025-01-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(default='default_file_name', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='year_published',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
